baseURL = 'https://snavleen.github.io/NKU-640/hugo/'
languageCode = 'en-us'
title = 'NKU 640 - Hugo Version'
theme = 'hugo-book'

# Book theme configuration
[params]
  # Sets color theme: light, dark or auto
  BookTheme = 'auto'

  # Controls table of contents visibility on right side of pages
  BookToC = true

  # Specify section of content to render as menu
  BookSection = 'docs'

  # Set source repository location
  BookRepo = 'https://github.com/SNavleen/NKU-640'

  # Enable "Edit this page" links for 'doc' page type
  BookEditPath = 'edit/main/hugo/content'

  # Configure the date format used on the pages
  BookDateFormat = 'January 2, 2006'

  # Enables search function with flexsearch
  BookSearch = true

  # Enables comments template on pages
  BookComments = false

  # Enables portable links and link checks in markdown pages
  BookPortableLinks = true

# Menu configuration
[menu]
[[menu.before]]
  name = "MkDocs Version"
  url = "https://snavleen.github.io/NKU-640/"
  weight = 1

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/SNavleen/NKU-640"
  weight = 10

# Taxonomy
[taxonomies]
  tag = 'tags'
